// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMxmA8ciMMBBd07_Alv8nbHYGZY9EBz2k',
    appId: '1:127610526426:web:6eb395a501d0b6e75c63e3',
    messagingSenderId: '127610526426',
    projectId: 'clone-a0293',
    authDomain: 'clone-a0293.firebaseapp.com',
    storageBucket: 'clone-a0293.firebasestorage.app',
    measurementId: 'G-48TFYFHQR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bOQ4t0n5UXOWCcbwGgo9LNpMIo_aeVc',
    appId: '1:127610526426:android:ebd2f4256fb8d04b5c63e3',
    messagingSenderId: '127610526426',
    projectId: 'clone-a0293',
    storageBucket: 'clone-a0293.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQ-7DiPrvadmYlYacjruwbF0xIZebCp8',
    appId: '1:127610526426:ios:c2870bd6793bc4435c63e3',
    messagingSenderId: '127610526426',
    projectId: 'clone-a0293',
    storageBucket: 'clone-a0293.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQ-7DiPrvadmYlYacjruwbF0xIZebCp8',
    appId: '1:127610526426:ios:c2870bd6793bc4435c63e3',
    messagingSenderId: '127610526426',
    projectId: 'clone-a0293',
    storageBucket: 'clone-a0293.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMxmA8ciMMBBd07_Alv8nbHYGZY9EBz2k',
    appId: '1:127610526426:web:ca8506607c9902055c63e3',
    messagingSenderId: '127610526426',
    projectId: 'clone-a0293',
    authDomain: 'clone-a0293.firebaseapp.com',
    storageBucket: 'clone-a0293.firebasestorage.app',
    measurementId: 'G-27C62NQDZJ',
  );
}
